apiVersion: v1
kind: ConfigMap
metadata:
  name: fog-agent-env
  namespace: fog3
data:
  # ---- Identity / logging ----
  FOG_NAME: fog3
  LOG_PREFIX: "[fog-agent][fog3]"

  # ---- MQTT endpoints ----
  FOG_MQTT_HOST: mqtt.fog3.svc.cluster.local
  FOG_MQTT_PORT: "1883"
  MQTT_HOST: mqtt.fog3.svc.cluster.local
  MQTT_PORT: "1883"

  CLOUD_MQTT_HOST: mqtt.cloud.svc.cluster.local
  CLOUD_MQTT_PORT: "1883"

  # ---- Fog events (match what fog publishes today) ----
  TOPIC_EDGE_MODEL_RECEIVED: fog/events/edge-model-received
  TOPIC_AGGREGATION_COMPLETE: fog/events/aggregation-complete
  TOPIC_CLOUD_MODEL_DOWNLINK: fog/events/cloud-model-downlink

  # ---- Commands fog-agent publishes back to fog node ----
  TOPIC_AGENT_COMMANDS: fog/agent/commands

  # ---- Cloud → fog control (listen to your bridge topic) ----
  TOPIC_CLOUD_TO_FOG_TARGETED: "cloud/agent/fog/fog3/commands"
  TOPIC_CLOUD_TO_FOG_BROADCAST: cloud/fog/command  # what your cloud bridge already uses

  # ---- Policy/Bandit defaults ----
  # Use the same ID format as your fog logs (edgeX_fog1, not edgeX-fog1)
  BANDIT_ARMS: edge1_fog3,edge2_fog3,edge3_fog3
  BANDIT_EPSILON: "0.1"
  ORCH_DEFAULT_QUOTA: "0.3"
  ORCH_DEFAULT_PRESSURE: "0.4"
  FOG_AGENT_SELECT_K: "2"

  # ---- Behavior toggles ----
  FOG_PURGE_AMQP_ON_BOOT: "true"
  FOG_PURGE_EDGE_MODELS_ON_BOOT: "true"
  FOG_PURGE_MQTT_RETAINED_ON_BOOT: "true"
  FOG_IGNORE_CLOUD_RETAINED_SECS: "10"
  FOG_MQTT_CLEAN_SESSION: "false"

