apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge2-fog2
  namespace: edge
spec:
  replicas: 1
  selector:
    matchLabels: { app: edge2-fog2 }
  template:
    metadata:
      labels: { app: edge2-fog2 }
    spec:
      # Schedule on the physical node edge2-fog2
      nodeSelector:
        role: edge2-fog2
      imagePullSecrets:
        - name: regcred
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: fix-perms-models
          image: busybox:1.36
          command: [ "sh","-c","mkdir -p /app/models && chown -R 1000:1000 /app/models && chmod -R ug+rwX /app/models" ]
          volumeMounts:
            - name: models
              mountPath: /app/models
      containers:
        - name: app
          image: docker.io/mipeda150/fedgrid-edge:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef: { name: edge2-fog2-env }
          volumeMounts:
            # Mount the single CSV file into the expected container path
            - name: input
              mountPath: /app/data/input_data.csv
              subPath: input_data.csv
            # (optional) persist models on the node
            - name: models
              mountPath: /app/models
            - name: host-sys
              mountPath: /host_sys
              readOnly: true
          readinessProbe:
            tcpSocket: { port: 8081 }
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: input
          persistentVolumeClaim: { claimName: edge2-fog2-input-pvc }
        - name: models
          hostPath:
            path: /var/lib/fedgrid/edge2-fog2/models
            type: DirectoryOrCreate
        - name: host-sys
          hostPath:
            path: /sys
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: edge2-fog2
  namespace: edge
spec:
  selector: { app: edge2-fog2 }
  ports:
    - name: http
      port: 8081
      targetPort: 8081

