apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge3-fog1
  namespace: edge
spec:
  replicas: 1
  selector: { matchLabels: { app: edge3-fog1 } }
  template:
    metadata: { labels: { app: edge3-fog1 } }
    spec:
      nodeSelector:
        tier: cloud
        logical-edge: edge3-fog1
      imagePullSecrets: [ { name: regcred } ]
      securityContext: { runAsUser: 1000, runAsGroup: 1000, fsGroup: 1000 }
      containers:
        - name: app
          image: docker.io/mipeda150/fedgrid-edge:latest
          ports: [ { containerPort: 8081 } ]
          envFrom: [ { configMapRef: { name: edge3-fog1-env } } ]
          volumeMounts:
            - { name: input, mountPath: /app/data/input_data.csv, subPath: input_data.csv }
            - { name: host-sys, mountPath: /host_sys, readOnly: true }
          readinessProbe:
            tcpSocket: { port: 8081 }
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: input
          persistentVolumeClaim: { claimName: edge3-fog1-input-pvc }
        - name: host-sys
          hostPath:
            path: /sys
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: edge3-fog1
  namespace: edge
spec:
  selector: { app: edge3-fog1 }
  ports: [ { name: http, port: 8081, targetPort: 8081 } ]

