apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge1-fog3
  namespace: edge
spec:
  replicas: 1
  selector:
    matchLabels: { app: edge1-fog3 }
  template:
    metadata:
      labels: { app: edge1-fog3 }
    spec:
      # Schedule on the physical node edge1-fog3
      nodeSelector:
        role: edge1-fog3
      imagePullSecrets:
        - name: regcred
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: app
          image: docker.io/mipeda150/fedgrid-edge:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef: { name: edge1-fog3-env }
          volumeMounts:
            # Mount the single CSV file into the expected container path
            - name: input
              mountPath: /app/data/input_data.csv
              subPath: input_data.csv
            # (optional) persist models on the node
            - name: models
              mountPath: /app/models
            - name: host-sys
              mountPath: /host_sys
              readOnly: true
          readinessProbe:
            tcpSocket: { port: 8081 }
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: input
          persistentVolumeClaim: { claimName: edge1-fog3-input-pvc }
        - name: models
          hostPath:
            path: /var/lib/fedgrid/edge1-fog3/models
            type: DirectoryOrCreate
        - name: host-sys
          hostPath:
            path: /sys
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: edge1-fog3
  namespace: edge
spec:
  selector: { app: edge1-fog3 }
  ports:
    - name: http
      port: 8081
      targetPort: 8081

